export const images = {

}

export const icons = {
    cross: require('../../assets/icons/cross.png'),
    backarrow: require('../../assets/icons/backarrow.png'),
    history: require('../../assets/icons/history.png'),
    search: require('../../assets/icons/search.png'),
    signout: require('../../assets/icons/signout.png'),
    settings: require('../../assets/icons/settings.png'),
    wallet: require('../../assets/icons/wallet.png'),
    bell: require('../../assets/icons/bell.png'),
    document: require('../../assets/icons/document.png'),
    person: require('../../assets/icons/person.png'),
    question: require('../../assets/icons/question.png'),
    shield: require('../../assets/icons/shield.png'),
    info: require('../../assets/icons/info.png'),
    open_eye: require('../../assets/icons/open_eye.png'),
    more_options: require('../../assets/icons/more_options.png'),
    filter: require('../../assets/icons/filter.png'),
    down: require('../../assets/icons/down.png'),
    close_eye: require('../../assets/icons/close_eye.png'),
    encircle: require('../../assets/icons/encircle.png'),
    outerHeaderLogo: require('../../assets/icons/outerHeaderLogo.png'),
    cross_white: require('../../assets/icons/cross_white.png'),
    dismiss_toast: require('../../assets/icons/dismiss_toast.png'),
    onBoarding: require('../../assets/icons/onBoarding.png'),
    copy: require('../../assets/icons/copy.png'),
    defaultImage: require('../../assets/icons/defaultImage.png'),
    backgroundDashboard: require('../../assets/icons/backgroundDashboard.png'),
    send: require('../../assets/icons/send.png'),
    receive: require('../../assets/icons/receive.png'),
    home: require('../../assets/icons/home.png'),
    stats: require('../../assets/icons/stats.png'),
    profile: require('../../assets/icons/profile.png'),
    marketplace: require('../../assets/icons/marketplace.png'),
    ethnetlogo: require('../../assets/icons/ethnetlogo.png'),
    netcross: require('../../assets/icons/netcross.png'),
    ethLogo: require('../../assets/icons/ethLogo.png'),
    mpLogo: require('../../assets/icons/mpLogo.png'),
    backgroundmp: require('../../assets/icons/backgroundmp.png'),
    addNft: require('../../assets/icons/addNft.png')
}