export enum NAVIGATIONS {
    // OUTER
    OUTER_NAV = "OUTER_NAV",
    INNER_NAV = "INNER_NAV",
    ONBOARDING_SCREEN = "ONBOARDING_SCREEN",
    LOGIN_SCREEN= "LOGIN_SCREEN",
    SIGNUP_SCREEN= "SIGNUP_SCREEN",
    TERMS_SCREEN= "TERMS_SCREEN",
    POLICY_SCREEN= "POLICY_SCREEN",
    //Inner
    INNER_TAB_NAVIGATION = "INNER_TAB_NAVIGATION",
    HOME_SCREEN= "HOME_SCREEN",
    MARKETPLACE_SCREEN= "MARKETPLACE_SCREEN",
    STATS_SCREEN= "STATS_SCREEN",
    PROFILE_SCREEN= "PROFILE_SCREEN",
    SEND_ETH_SCREEN= "SEND_ETH_SCREEN",
    RECEIVE_ETH_SCREEN= "RECEIVE_ETH_SCREEN",
    NFT_DETAILS_SCREEN= "NFT_DETAILS_SCREEN",
    BUY_NFT_SCREEN= "BUY_NFT_SCREEN",
    SELL_NFT_SCREEN= "SELL_NFT_SCREEN"
}